[workspace]
exclude = [
  "examples/example-plugin",
  "examples/example-rust-runtime",
  "bindings/rust-plugin",
]
members = [
  "fp-bindgen",
  "fp-bindgen-support",
  "macros",
  "examples/example-protocol",
  "examples/example-types",
]
