[package]
name = "example-plugin"
version = "0.1.0"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
once_cell = "1"
rmp-serde = "0.15"
serde = { version = "1.0", features = ["derive"] }
