[package]
name = "example-bindings"
version = "1.0.0"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[dependencies]
fp-bindgen-support = { path = "../../fp-bindgen-support", version = "1.0.0-rc.1", features = ["async", "guest", "http"] }
http = { version = "0.2" }
once_cell = { version = "1.4" }
rmp-serde = { version = "1.0" }
serde = { version = "1.0", features = ["derive"] }
serde_bytes = { version = "0.11" }
time = { version = "0.3", features = ["serde-human-readable"] }
