[package]
name = "fp-bindgen-macros"
version = "0.1.0"
authors = ["Fiberplane <info@fiberplane.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11"
once_cell = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["full", "extra-traits"] }
